function setup() {
    createCanvas(400, 400);
  }
  
  function draw() {
    let c = color(255, 210, 20);
  let v = color( 244, 10, 20 );
  let b = color(255, 200, 255 );
  let x = color(2, 150, 50);
    background(30, 50, 70);
    fill(x);
    square(-1,170, 409);
    fill(b);
    ellipse(200, 240, 233, 96);
    fill(c);
    ellipse(200, 230, 175, 71);
    fill(v);
    ellipse(200, 225, 150, 45);
    fill(c);
     ellipse(200, 240, 180, 50);
    fill(b);
    line(190, 205, 200, 215);
    line(170, 205, 180, 215);
    line(150, 210, 160, 217);
    line(210, 205, 220, 215);
    fill(c);
    triangle(17, 20, 107, 20, 62, -25);
    rect(12, 20, 100, 180);
    ellipse(62, 200, 100, 20);
    ellipse(62, 20, 100, 20);
     ellipse(62, 15, 77, 10);
    fill(v)
    text( "Mustard", 40, 50)
    
  }